### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by OmegaLeFoxWolf** [zenyr/PocoHud3#55] opened 2017-07-21 21:11 UTC
Fri Jul 21 16:59:25 2017

Application has crashed: C++ exception
mods/PocoHud3/poco/../poco/Hud3.lua:158: attempt to compare string with number

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                       nvd3dum  (???)     QueryOglResource                                    
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
Application version : 1.74.281.
CPU : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
DirectX : 12.0 
GPU : NVIDIA GeForce GTX 1060 / nvldumd.dll[22.21.13.8178]
Language : @ID94cca2fdaccfc2cd@
Memory :     16336MB 800KB
OS : 6.2.9200 () 0x300-0x1 (64 bits)
Physics : threaded
Renderer : DX9 threaded
Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by zenyr** [comment] 2017-07-22 09:26
I am pretty sure this is dupe of the issue #51 which is fixed on latest github release.

**Closed by zenyr** 2017-07-22 09:26 UTC
